//! systemd/launchd service install and management.
//!
//! Linux: writes ~/.config/systemd/user/b3.service (Restart=on-failure)
//! macOS: writes ~/Library/LaunchAgents/ai.babel3.plist (RunAtLoad=true)
//!
//! All functions are idempotent and safe to call multiple times.
//! Errors from optional steps (linger, daemon-reload) are logged at debug
//! level and do not propagate — the caller should never fail because of
//! service registration.

use std::path::PathBuf;
use std::process::Command;

// ── Public API ────────────────────────────────────────────────────────

/// Install and enable the b3 service for the current platform.
/// Silently no-ops if the platform doesn't support it or systemd is unavailable.
/// Returns Ok(true) if the service was installed, Ok(false) if skipped.
pub fn install() -> anyhow::Result<bool> {
    #[cfg(target_os = "linux")]
    {
        if !systemd_available() {
            tracing::debug!("service::install: systemd not available, skipping");
            return Ok(false);
        }
        install_systemd()
    }
    #[cfg(target_os = "macos")]
    {
        install_launchd()
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        tracing::debug!("service::install: platform not supported, skipping");
        Ok(false)
    }
}

/// Remove the b3 service registration.
/// Silently no-ops if no service is registered.
pub fn uninstall() -> anyhow::Result<()> {
    #[cfg(target_os = "linux")]
    {
        uninstall_systemd()
    }
    #[cfg(target_os = "macos")]
    {
        uninstall_launchd()
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        Ok(())
    }
}

/// Returns true if a b3 service is currently registered on disk.
pub fn is_installed() -> bool {
    #[cfg(target_os = "linux")]
    {
        systemd_unit_path().map(|p| p.exists()).unwrap_or(false)
    }
    #[cfg(target_os = "macos")]
    {
        launchd_plist_path().map(|p| p.exists()).unwrap_or(false)
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        false
    }
}

// ── Linux / systemd ───────────────────────────────────────────────────

#[cfg(target_os = "linux")]
fn systemd_unit_path() -> anyhow::Result<PathBuf> {
    let home = std::env::var("HOME").unwrap_or_else(|_| {
        dirs_home().unwrap_or_else(|| PathBuf::from("/tmp")).to_string_lossy().into_owned()
    });
    Ok(PathBuf::from(home).join(".config/systemd/user/b3.service"))
}

#[cfg(target_os = "linux")]
fn systemd_available() -> bool {
    // Probe the user manager specifically (not the system manager).
    // `systemctl --user status` exits 0 when the user manager is running,
    // non-zero when systemd is absent or the user session manager isn't up.
    Command::new("systemctl")
        .args(["--user", "status"])
        .output()
        .map(|o| {
            // Exit codes: 0 = running, 1/3 = degraded/stopped (manager exists),
            // 127 = command not found (no systemd). Accept 0 and 1/3 as "available".
            let stdout = String::from_utf8_lossy(&o.stdout);
            let stderr = String::from_utf8_lossy(&o.stderr);
            // Command not found or dbus error → not available
            if stderr.contains("Failed to connect") || stderr.contains("not found") {
                return false;
            }
            // Any recognisable systemd output → available
            o.status.success()
                || stdout.contains("systemd")
                || stdout.contains(".service")
        })
        .unwrap_or(false)
}

#[cfg(target_os = "linux")]
fn install_systemd() -> anyhow::Result<bool> {
    let unit_path = systemd_unit_path()?;

    // Ensure directory exists
    if let Some(parent) = unit_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let exe = std::env::current_exe()
        .unwrap_or_else(|_| PathBuf::from("b3"));

    let unit_content = format!(
        "# Auto-generated by b3 — do not edit manually.\n\
         # ExecStart path is baked at registration time. Run `b3 start` again\n\
         # after upgrading the b3 binary to refresh the path.\n\
         [Unit]\n\
         Description=Babel3 agent daemon\n\
         After=network.target\n\
         \n\
         [Service]\n\
         Type=forking\n\
         PIDFile=%h/.b3/b3.pid\n\
         ExecStart={exe} start\n\
         Restart=on-failure\n\
         RestartSec=5s\n\
         Environment=HOME=%h\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        exe = exe.display()
    );

    // Write unit file (idempotent — overwrite if already exists)
    std::fs::write(&unit_path, &unit_content)?;
    tracing::debug!("service::install: wrote {}", unit_path.display());

    // Enable linger — critical for WSL persistence across boots
    let username = std::env::var("USER")
        .unwrap_or_else(|_| whoami_fallback());
    let linger_result = Command::new("loginctl")
        .args(["enable-linger", &username])
        .output();
    match linger_result {
        Ok(o) if o.status.success() => {
            tracing::debug!("service::install: linger enabled for {username}");
        }
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            tracing::debug!("service::install: loginctl enable-linger failed: {stderr}");
            eprintln!(
                "  Note: Could not enable linger — b3 may not start on boot without a login session.\n\
                 Run: loginctl enable-linger {username}"
            );
        }
        Err(e) => {
            tracing::debug!("service::install: loginctl not found: {e}");
        }
    }

    // Reload systemd user daemon so it sees the new unit
    let _ = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output();

    // Enable for future boots (do NOT start — b3 start is already running the daemon)
    let enable_result = Command::new("systemctl")
        .args(["--user", "enable", "b3"])
        .output();
    match enable_result {
        Ok(o) if o.status.success() => {
            tracing::debug!("service::install: systemd unit enabled");
        }
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            tracing::debug!("service::install: systemctl enable failed: {stderr}");
        }
        Err(e) => {
            tracing::debug!("service::install: systemctl not available: {e}");
        }
    }

    Ok(true)
}

#[cfg(target_os = "linux")]
fn uninstall_systemd() -> anyhow::Result<()> {
    // Disable the unit (ignore errors — unit may not exist)
    let _ = Command::new("systemctl")
        .args(["--user", "disable", "b3"])
        .output();

    // Remove the unit file
    if let Ok(path) = systemd_unit_path() {
        if path.exists() {
            std::fs::remove_file(&path)?;
            tracing::debug!("service::uninstall: removed {}", path.display());
        }
    }

    // Reload so systemd forgets the unit
    let _ = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output();

    Ok(())
}

// ── macOS / launchd ───────────────────────────────────────────────────

#[cfg(target_os = "macos")]
fn launchd_plist_path() -> anyhow::Result<PathBuf> {
    let home = std::env::var("HOME").unwrap_or_else(|_| {
        dirs_home().unwrap_or_else(|| PathBuf::from("/tmp")).to_string_lossy().into_owned()
    });
    Ok(PathBuf::from(home).join("Library/LaunchAgents/ai.babel3.plist"))
}

#[cfg(target_os = "macos")]
fn install_launchd() -> anyhow::Result<bool> {
    let plist_path = launchd_plist_path()?;

    // Ensure directory exists
    if let Some(parent) = plist_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let exe = std::env::current_exe()
        .unwrap_or_else(|_| PathBuf::from("b3"));

    let plist_content = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"\n\
         \t\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \t<key>Label</key>\n\
         \t<string>ai.babel3</string>\n\
         \t<key>ProgramArguments</key>\n\
         \t<array>\n\
         \t\t<string>{exe}</string>\n\
         \t\t<string>start</string>\n\
         \t</array>\n\
         \t<key>RunAtLoad</key>\n\
         \t<true/>\n\
         \t<key>StandardOutPath</key>\n\
         \t<string>/tmp/b3-launchd.log</string>\n\
         \t<key>StandardErrorPath</key>\n\
         \t<string>/tmp/b3-launchd.log</string>\n\
         </dict>\n\
         </plist>\n",
        exe = exe.display()
    );

    // Skip unload/reload if the plist content is already identical.
    // launchctl unload on a running service triggers a restart race: launchd
    // may relaunch the old process between unload and the new load, creating
    // two concurrent daemon instances. Safe to skip when nothing changed.
    if plist_path.exists() {
        let existing = std::fs::read_to_string(&plist_path).unwrap_or_default();
        if existing == plist_content {
            tracing::debug!("service::install: plist unchanged, skipping reload");
            return Ok(true);
        }
        // Content differs (e.g. exe path changed after upgrade) — unload before rewrite.
        let _ = Command::new("launchctl")
            .args(["unload", &plist_path.to_string_lossy()])
            .output();
    }

    std::fs::write(&plist_path, &plist_content)?;
    tracing::debug!("service::install: wrote {}", plist_path.display());

    let load_result = Command::new("launchctl")
        .args(["load", &plist_path.to_string_lossy()])
        .output();
    match load_result {
        Ok(o) if o.status.success() => {
            tracing::debug!("service::install: launchd plist loaded");
        }
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            tracing::debug!("service::install: launchctl load failed: {stderr}");
        }
        Err(e) => {
            tracing::debug!("service::install: launchctl not available: {e}");
        }
    }

    Ok(true)
}

#[cfg(target_os = "macos")]
fn uninstall_launchd() -> anyhow::Result<()> {
    if let Ok(plist_path) = launchd_plist_path() {
        if plist_path.exists() {
            // Unload before deleting
            let _ = Command::new("launchctl")
                .args(["unload", &plist_path.to_string_lossy()])
                .output();
            std::fs::remove_file(&plist_path)?;
            tracing::debug!("service::uninstall: removed {}", plist_path.display());
        }
    }
    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────

/// Fallback home directory via std::env when the `dirs` crate isn't available.
#[allow(dead_code)]
fn dirs_home() -> Option<PathBuf> {
    std::env::var("HOME").ok().map(PathBuf::from)
}

/// Last-resort username via `whoami` when $USER is not set.
#[allow(dead_code)]
fn whoami_fallback() -> String {
    Command::new("whoami")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "user".to_string())
}
